
const services = [
  { pageName: 'Brick',
    imgSrc: 'http://lorempixel.com/240/150/city/1',
    title: 'Chimneys & Brick',
    summary: 'The condition of your chimney is very important for many reasons. Even an unused chimney must be maintained to avoid water penetration that can cause exterior as well as interior damage.',
    subtitle1: 'Excellent Craftsmanship',
    content1: 'The condition of your chimney is very important for many reasons. Even an unused chimney must be maintained to avoid water penetration that can cause exterior as well as interior damage. The chimney requires several key components to be present in order for it to resist the harsh elements. Remember, the chimney stands above the structure and is exposed to the elements.',
    subtitle2: 'See the difference!',
    content2: 'The condition of your chimney is very important for many reasons. Even an unused chimney must be maintained to avoid water penetration that can cause exterior as well as interior damage.',
    link: '' },

  { pageName: 'Concrete',
    imgSrc: 'http://lorempixel.com/240/150/city/2',
    title: 'Concrete',
    summary: 'Concrete cracks are a common problem throughout the GTA. The majority of these cracks are caused by the failure to ensure proper reinforcement at time of installation. Concrete is useless without reinforcement.',
    subtitle1: 'Excellent Craftsmanship',
    content1: 'Concrete cracks are a common problem throughout the GTA. The majority of these cracks are caused by the failure to ensure proper reinforcement at time of installation. Concrete is useless without reinforcement. It is important to repair these cracks as when left unattended the cracks will widen with time and the freeze / thaw cycles will leave the concrete porous to the environment, especially water.',
    subtitle2: 'See the difference!',
    content2: 'This is an additional paragraph detailing all the extra stuff about this service.',
    link: '' },

  { pageName: 'Foundation',
    imgSrc: 'http://lorempixel.com/240/150/city/3',
    title: 'Foundation',
    summary: 'When Three Little Pigs Masonry is hired to install flagstone, the existing foundation must be sound or the life of the final product will be short.',
    subtitle1: 'Excellent Craftsmanship',
    content1: 'When Three Little Pigs Masonry is hired to install flagstone, the existing foundation must be sound or the life of the final product will be short. What is a sound foundation? The foundation must have been installed with all the necessary and essential components for it to withstand the earth’s shifting and our climate (frost).',
    subtitle2: 'See the difference!',
    content2: 'This is an additional paragraph detailing all the extra stuff about this service.',
    link: '' },

  { pageName: 'Stone',
    imgSrc: 'http://lorempixel.com/240/150/city/4',
    title: 'Stone',
    summary: 'Stone refacing has become a popular way to enhance the exterior beauty of your home using stone products.',
    subtitle1: 'Excellent Craftsmanship',
    content1: 'Stone refacing has become a popular way to enhance the exterior beauty of your home using stone products. Real stone refacing allows us to change the look of your home through custom stone renovations eliminating the need to move away from your existing neighbourhood while achieving an updated look for your home or business.',
    subtitle2: 'See the difference!',
    content2: 'This is an additional paragraph detailing all the extra stuff about this service.',
    link: '' },

  { pageName: 'Walls',
    imgSrc: 'http://lorempixel.com/240/150/city/5',
    title: 'Walls & Windows',
    summary: 'Properly installed window sills are essential for the complete building envelope. Brick window sills tend to breakdown for a number of reasons.',
    subtitle1: 'Excellent Craftsmanship',
    content1: 'Properly installed window sills are essential for the complete building envelope. Brick window sills tend to breakdown for a number of reasons. They are installed with an insufficient slope downwards and water sits on the brick instead of flowing away from the window. There are so many mortar joints and therefore too many possible entries for water to penetrate.',
    subtitle2: 'See the difference!',
    content2: 'This is an additional paragraph detailing all the extra stuff about this service.',
    link: '' },

  { pageName: 'Basement',
    imgSrc: 'http://lorempixel.com/240/150/city/6',
    title: 'Basement',
    summary: 'With basement waterproofing, usually we have to excavate the problem area or areas right down to the footing. We then check the weeping tile to make sure that after we leave the area that it is in good shape.',
    content1: 'With basement waterproofing, usually we have to excavate the problem area or areas right down to the footing. We then check the weeping tile to make sure that after we leave the area that it is in good shape. If it too is defective, we must repair it.',
    subtitle2: 'See the difference!',
    content2: 'This is an additional paragraph detailing all the extra stuff about this service.',
    link: '' },
];

export default services;
